version: '3'
services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hiface
      PGDATA: /var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8880:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tinhvan.com
      PGADMIN_DEFAULT_PASSWORD: admin123
volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
